<?php
/**
 * The six provenance states — the single PHP source of truth.
 *
 * Mirrors the brand tokens from the design system (Evidence Green signature,
 * subordinate state colors used only at small scale) and is localized to the
 * editor so JS and PHP never drift.
 *
 * @package KineticGain\AIEvidence
 */

namespace KineticGain\AIEvidence;

defined( 'ABSPATH' ) || exit;

/**
 * Provenance state registry.
 */
class States {

	/**
	 * The default state when none is set.
	 */
	const DEFAULT_STATE = 'verified';

	/**
	 * Return the full state registry.
	 *
	 * @return array<string,array<string,string>> Map of state slug => descriptor.
	 */
	public static function all() {
		$states = array(
			'verified'      => array(
				'label'       => __( 'Verified', 'ai-evidence-block' ),
				'description' => __( 'Author-written and self-attested.', 'ai-evidence-block' ),
				'color'       => '#0F5132',
				'tint'        => '#E6EFE9',
				'underline'   => 'solid',
				'icon'        => 'verified',
			),
			'cited'         => array(
				'label'       => __( 'Cited', 'ai-evidence-block' ),
				'description' => __( 'Backed by a link, document or external record.', 'ai-evidence-block' ),
				'color'       => '#1E3A8A',
				'tint'        => '#E5EAF4',
				'underline'   => 'solid',
				'icon'        => 'cited',
			),
			'ai-assisted'   => array(
				'label'       => __( 'AI-assisted', 'ai-evidence-block' ),
				'description' => __( 'AI helped draft, but a human reviewed and edited.', 'ai-evidence-block' ),
				'color'       => '#B45309',
				'tint'        => '#F8EEDA',
				'underline'   => 'dashed',
				'icon'        => 'ai-assisted',
			),
			'ai-generated'  => array(
				'label'       => __( 'AI-generated', 'ai-evidence-block' ),
				'description' => __( 'Generated by AI without human edits, disclosed for transparency.', 'ai-evidence-block' ),
				'color'       => '#B45309',
				'tint'        => '#F8EEDA',
				'underline'   => 'dashed',
				'icon'        => 'ai-generated',
			),
			'auto-detected' => array(
				'label'       => __( 'Auto-detected', 'ai-evidence-block' ),
				'description' => __( 'Flagged as likely AI-generated; awaiting author confirmation.', 'ai-evidence-block' ),
				'color'       => '#B45309',
				'tint'        => '#F8EEDA',
				'underline'   => 'dotted',
				'icon'        => 'auto-detected',
			),
			'disputed'      => array(
				'label'       => __( 'Disputed', 'ai-evidence-block' ),
				'description' => __( 'Flagged for review or contested by readers or editors.', 'ai-evidence-block' ),
				'color'       => '#9F1239',
				'tint'        => '#F4E1E6',
				'underline'   => 'wavy',
				'icon'        => 'disputed',
			),
		);

		/**
		 * Filter the provenance state registry.
		 *
		 * Adding states is supported; the renderer and mapper degrade gracefully
		 * for unknown states (treated as neutral/background).
		 *
		 * @param array<string,array<string,string>> $states State registry.
		 */
		return (array) apply_filters( 'kgaeb_states', $states );
	}

	/**
	 * The list of valid state slugs.
	 *
	 * @return string[] State slugs.
	 */
	public static function slugs() {
		return array_keys( self::all() );
	}

	/**
	 * Whether a slug is a known state.
	 *
	 * @param string $state State slug.
	 * @return bool True when valid.
	 */
	public static function is_valid( $state ) {
		return array_key_exists( (string) $state, self::all() );
	}

	/**
	 * Sanitize a raw value to a known state slug.
	 *
	 * @param mixed $state Raw value.
	 * @return string A valid state slug; defaults to the default state.
	 */
	public static function sanitize( $state ) {
		$state = sanitize_key( (string) $state );
		return self::is_valid( $state ) ? $state : self::DEFAULT_STATE;
	}

	/**
	 * Get a single state descriptor.
	 *
	 * @param string $state State slug.
	 * @return array<string,string> Descriptor, falling back to the default state.
	 */
	public static function get( $state ) {
		$all   = self::all();
		$state = (string) $state;
		if ( isset( $all[ $state ] ) ) {
			return $all[ $state ];
		}
		return $all[ self::DEFAULT_STATE ];
	}

	/**
	 * The human-readable label for a state.
	 *
	 * @param string $state State slug.
	 * @return string Label.
	 */
	public static function label( $state ) {
		$descriptor = self::get( $state );
		return $descriptor['label'];
	}
}
