<?php
/**
 * Provenance mapping — the bridge between the editor's authorship vocabulary
 * and machine-readable provenance standards.
 *
 * ---------------------------------------------------------------------------
 *  EDITOR-JUDGMENT SURFACE
 *  -----------------------
 *  The AI Evidence Format describes *citations*, not *authorship*, so its
 *  `synthesis_role` enum has no native word for "a human wrote this" or "AI
 *  drafted this." The table below is therefore an editorial decision: how each
 *  authorship state best maps onto (1) the spec's `synthesis_role`, (2) the
 *  IPTC `digitalSourceType` controlled vocabulary (the C2PA-adjacent provenance
 *  standard), and (3) a short human credit phrase.
 *
 *  These are defensible defaults, not gospel. Override any row with the
 *  `kgaeb_provenance_map` filter — no need to edit this file.
 * ---------------------------------------------------------------------------
 *
 * @package KineticGain\AIEvidence
 */

namespace KineticGain\AIEvidence;

defined( 'ABSPATH' ) || exit;

/**
 * Maps provenance states to spec and standards vocabularies.
 */
class Provenance {

	/**
	 * IPTC DigitalSourceType controlled-vocabulary base URI.
	 *
	 * @see https://cv.iptc.org/newscodes/digitalsourcetype/
	 */
	const IPTC_BASE = 'https://cv.iptc.org/newscodes/digitalsourcetype/';

	/**
	 * The mapping table: state slug => { synthesis_role, iptc, credit }.
	 *
	 * - synthesis_role: one of supporting | contradicting | partial | background
	 *   (the AI Evidence Format enum). For authorship disclosure the marked text
	 *   is the claim and its source supports it, so most states are "supporting";
	 *   contested content is "contradicting"; uncertain content is "partial".
	 * - iptc: an IPTC DigitalSourceType code describing how the content originated,
	 *   or '' to assert NO source type (used when origin is only suspected, not
	 *   confirmed — emitting an affirmative code there would overclaim provenance).
	 * - credit: a translatable, human-facing credit phrase template. `%s` is the
	 *   reviewer or model label when relevant.
	 *
	 * @return array<string,array<string,string>> The provenance map.
	 */
	public static function map() {
		$map = array(
			'verified'      => array(
				'synthesis_role' => 'supporting',
				'iptc'           => 'digitalCapture',
				/* translators: %s: human reviewer name. */
				'credit'         => __( 'Verified by %s', 'ai-evidence-block' ),
			),
			'cited'         => array(
				'synthesis_role' => 'supporting',
				'iptc'           => 'digitalCapture',
				'credit'         => __( 'Cited source', 'ai-evidence-block' ),
			),
			'ai-assisted'   => array(
				'synthesis_role' => 'supporting',
				'iptc'           => 'compositeWithTrainedAlgorithmicMedia',
				/* translators: %s: human reviewer name. */
				'credit'         => __( 'AI-assisted, reviewed by %s', 'ai-evidence-block' ),
			),
			'ai-generated'  => array(
				'synthesis_role' => 'supporting',
				'iptc'           => 'trainedAlgorithmicMedia',
				/* translators: %s: AI model label. */
				'credit'         => __( 'AI-generated by %s', 'ai-evidence-block' ),
			),
			'auto-detected' => array(
				'synthesis_role' => 'partial',
				// Deliberately no IPTC code. "Auto-detected" is an *unconfirmed*
				// suspicion, and IPTC DigitalSourceType has no "suspected AI" term.
				// Mapping it to trainedAlgorithmicMedia ("Created using Generative
				// AI") would publish a definitive provenance claim the editor has not
				// confirmed, so the source type is left unasserted (origin unknown).
				// A site that treats auto-detection as authoritative can re-add a
				// code via the `kgaeb_provenance_map` filter.
				'iptc'           => '',
				'credit'         => __( 'Auto-detected as likely AI-generated', 'ai-evidence-block' ),
			),
			'disputed'      => array(
				'synthesis_role' => 'contradicting',
				'iptc'           => 'digitalCapture',
				'credit'         => __( 'Disputed', 'ai-evidence-block' ),
			),
		);

		/**
		 * Filter the provenance mapping table.
		 *
		 * Lets a site re-map any authorship state to a different synthesis role,
		 * IPTC DigitalSourceType, or credit phrase without editing the plugin.
		 *
		 * @param array<string,array<string,string>> $map The provenance map.
		 */
		return (array) apply_filters( 'kgaeb_provenance_map', $map );
	}

	/**
	 * Get the mapping descriptor for a state, falling back to a neutral default.
	 *
	 * @param string $state State slug.
	 * @return array<string,string> { synthesis_role, iptc, credit }.
	 */
	public static function for_state( $state ) {
		$map   = self::map();
		$state = (string) $state;

		if ( isset( $map[ $state ] ) ) {
			return $map[ $state ];
		}

		// Unknown/filter-added state: cite it as background context, human origin.
		return array(
			'synthesis_role' => 'background',
			'iptc'           => 'digitalCapture',
			'credit'         => '',
		);
	}

	/**
	 * The spec `synthesis_role` for a state.
	 *
	 * @param string $state State slug.
	 * @return string supporting | contradicting | partial | background.
	 */
	public static function synthesis_role( $state ) {
		$descriptor = self::for_state( $state );
		return $descriptor['synthesis_role'];
	}

	/**
	 * The full IPTC DigitalSourceType URI for a state.
	 *
	 * @param string $state State slug.
	 * @return string Absolute IPTC NewsCodes URI, or '' when the state asserts no
	 *                source type (a blank `iptc` in the map, e.g. auto-detected).
	 */
	public static function digital_source_type( $state ) {
		$descriptor = self::for_state( $state );

		// A blank `iptc` means "origin not asserted" — return '' rather than a bare
		// base URI so every consumer drops the additionalType / data-aeb-source-type
		// instead of publishing a meaningless or overclaiming provenance value.
		if ( '' === $descriptor['iptc'] ) {
			return '';
		}

		return self::IPTC_BASE . $descriptor['iptc'];
	}

	/**
	 * Build the resolved, human-facing credit line for a claim.
	 *
	 * @param string $state    State slug.
	 * @param string $reviewer Human reviewer/verifier name.
	 * @param string $model    Resolved model label.
	 * @return string Credit line, or '' when the template needs data it lacks.
	 */
	public static function credit_line( $state, $reviewer = '', $model = '' ) {
		$descriptor = self::for_state( $state );
		$template   = $descriptor['credit'];

		if ( '' === $template ) {
			return '';
		}

		// Templates with a placeholder need their substitution value present.
		if ( false !== strpos( $template, '%s' ) ) {
			$value = '';
			if ( 'ai-generated' === $state ) {
				$value = $model;
			} else {
				$value = $reviewer;
			}

			if ( '' === trim( $value ) ) {
				// No value to fill in — drop the placeholder clause gracefully.
				return self::label_only( $state );
			}

			return sprintf( $template, $value );
		}

		return $template;
	}

	/**
	 * A credit phrase with no substitution, derived from the state label.
	 *
	 * Used when a `%s` template lacks its value (e.g. AI-assisted with no
	 * reviewer recorded).
	 *
	 * @param string $state State slug.
	 * @return string Bare label-based credit.
	 */
	private static function label_only( $state ) {
		return States::label( $state );
	}
}
